Repository mundipagg/magento-module, pull requests merged in 2018-10, with the labels that each got.

#194 Fix php incompatibilities and others bugs
  app/code/community/Uecommerce/Mundipagg/Helper/TwoCreditCardsPostNotificationHandler.php
  app/code/community/Uecommerce/Mundipagg/Helper/Util.php
  app/code/community/Uecommerce/Mundipagg/Model/Standard.php
  app/code/community/Uecommerce/Mundipagg/etc/integrity/integrityCheck
Labels: Bug, Ready

#196 Added NSU information on Payment Information
  app/code/community/Uecommerce/Mundipagg/controllers/StandardController.php
  app/code/community/Uecommerce/Mundipagg/etc/integrity/IntegrityEngine.php
  app/code/community/Uecommerce/Mundipagg/etc/integrity/integrityCheck
  app/design/adminhtml/default/default/template/mundipagg/payment/info/mundipagg.phtml
Labels: Feature, Ready

#199 Two Cards Semaphore fix
  app/code/community/Uecommerce/Mundipagg/Helper/TwoCreditCardsPostNotificationHandler.php
Labels: Bug, Ready

#200 Remove cvv from saved additional information
  app/code/community/Uecommerce/Mundipagg/Model/Standard.php
Labels: Bug, Enhancement, Ready

#201 Handle boleto url failure
  app/code/community/Uecommerce/Mundipagg/Model/Api.php
Labels: Bug, Ready

#203 Installment display fix
  app/code/community/Uecommerce/Mundipagg/Block/Info.php
  app/code/community/Uecommerce/Mundipagg/Helper/TwoCreditCardsPostNotificationHandler.php
  app/code/community/Uecommerce/Mundipagg/etc/integrity/integrityCheck
Labels: Bug, Ready
