Repository mundipagg/magento-module, pull requests merged in 2018-03, with the labels that each got.

#126 Improve response log
  app/code/community/Uecommerce/Mundipagg/Model/Api.php
Labels: Enhancement

#128 Fixed undefined index notice on notification post flux
  app/code/community/Uecommerce/Mundipagg/Model/Api.php
Labels: Bug

#131 Fix order total when changing shipping method on two credit cards checkout.
  app/design/frontend/rwd/default/template/mundipagg/form.phtml
Labels: Bug, Ready

#133 Issue 153 patch 2 credit card balance with theme
  app/code/community/Uecommerce/Mundipagg/Helper/Log.php
  app/code/community/Uecommerce/Mundipagg/Model/Api.php
  app/code/community/Uecommerce/Mundipagg/Model/Creditcard.php
  app/code/community/Uecommerce/Mundipagg/Model/Standard.php
  app/design/frontend/base/default/template/mundipagg/form.phtml
  app/design/frontend/rwd/default/template/mundipagg/form.phtml
Labels: Bug
