Repository mundipagg/magento-module, pull requests merged in 2018-08, with the labels that each got.

#164 Checkout form style fix and log files download
  app/code/community/Uecommerce/Mundipagg/Helper/Log.php
  app/code/community/Uecommerce/Mundipagg/Model/Twocreditcards.php
  app/code/community/Uecommerce/Mundipagg/controllers/StandardController.php
  app/code/community/Uecommerce/Mundipagg/etc/integrity/IntegrityEngine.php
  app/code/community/Uecommerce/Mundipagg/etc/integrity/integrityCheck
  app/design/frontend/base/default/template/mundipagg/form.phtml
Labels: Bug, Enhancement, Feature, Ready

#165 Integrity check from integrity file
  app/code/community/Uecommerce/Mundipagg/etc/integrity/IntegrityEngine.php
  app/code/community/Uecommerce/Mundipagg/etc/integrity/integrityCheck
  integrityDeploy.php
Labels: Enhancement, Ready

#167 Fix blank installments
  app/code/community/Uecommerce/Mundipagg/Model/Standard.php
  app/design/frontend/base/default/template/mundipagg/form.phtml
Labels: Bug, Ready

#168 Add Order info on integrity check
  app/code/community/Uecommerce/Mundipagg/controllers/StandardController.php
  app/code/community/Uecommerce/Mundipagg/etc/integrity/integrityCheck
Labels: Enhancement, Ready

#169 Fix extra interest on order
  app/code/community/Uecommerce/Mundipagg/Helper/Transaction.php
  app/code/community/Uecommerce/Mundipagg/etc/integrity/integrityCheck
  app/design/frontend/base/default/template/mundipagg/form.phtml
Labels: Bug, Ready

#171 Fix rounding errors
  app/code/community/Uecommerce/Mundipagg/Helper/ProcessOrderStatus.php
  app/code/community/Uecommerce/Mundipagg/Helper/Transaction.php
Labels: Bug

#174 Create new two credit cards handler
  app/code/community/Uecommerce/Mundipagg/Helper/Invoice.php
  app/code/community/Uecommerce/Mundipagg/Helper/Transaction.php
  app/code/community/Uecommerce/Mundipagg/Helper/TwoCreditCardsPostNotificationHandler.php
  app/code/community/Uecommerce/Mundipagg/Helper/Util.php
  app/code/community/Uecommerce/Mundipagg/Model/Api.php
Labels: Bug, Ready

#176 Fix phone number on buyer information
  app/code/community/Uecommerce/Mundipagg/Model/Api.php
  app/code/community/Uecommerce/Mundipagg/etc/integrity/integrityCheck
Labels: Bug, Ready

#177 Fix some bugs and change the hold method
  app/code/community/Uecommerce/Mundipagg/Helper/TwoCreditCardsPostNotificationHandler.php
  app/code/community/Uecommerce/Mundipagg/Model/Observer.php
  app/code/community/Uecommerce/Mundipagg/controllers/StandardController.php
  app/code/community/Uecommerce/Mundipagg/etc/integrity/integrityCheck
Labels: Bug, Ready

#178 Fix some bugs and change the hold method
  app/code/community/Uecommerce/Mundipagg/Helper/TwoCreditCardsPostNotificationHandler.php
  app/code/community/Uecommerce/Mundipagg/Model/Observer.php
  app/code/community/Uecommerce/Mundipagg/controllers/StandardController.php
  app/code/community/Uecommerce/Mundipagg/etc/integrity/integrityCheck
Labels: Bug, Ready
