Repository mundipagg/magento-module, pull requests merged in 2018-07, with the labels that each got.

#155 Fix compatibility with php version
  app/code/community/Uecommerce/Mundipagg/Helper/Logger.php
  app/code/community/Uecommerce/Mundipagg/Model/Api.php
Labels: Bug, Ready

#157 Fix installment reset on checkout
  js/uecommerce/mundipagg.js
Labels: Bug, Ready

#159 Added Module Integrity Check
  .gitignore
  app/code/community/Uecommerce/Mundipagg/controllers/StandardController.php
  app/code/community/Uecommerce/Mundipagg/etc/integrity/IntegrityEngine.php
  app/code/community/Uecommerce/Mundipagg/etc/integrity/integrityCheck
  integrityDeploy.php
  modman
Labels: Feature, Ready

#161 Bug decimal cents fix
  app/code/community/Uecommerce/Mundipagg/Helper/ProcessOrderStatus.php
  app/code/community/Uecommerce/Mundipagg/Helper/Transaction.php
  app/code/community/Uecommerce/Mundipagg/Model/Api.php
  app/code/community/Uecommerce/Mundipagg/Model/Twocreditcards.php
Labels: Bug, Ready

#162 Add existence and readability check for integrity files
  app/code/community/Uecommerce/Mundipagg/etc/integrity/IntegrityEngine.php
  app/code/community/Uecommerce/Mundipagg/etc/integrity/integrityCheck
Labels: Enhancement, Ready
